### ISSUE TITLE
Updating to latest Yakindu breaks active(region.state) references

### ISSUE THREAD

**Issue by elgeekomm** [Yakindu/statecharts#1294]
After updating Yakindu via Eclipse update, the following code no longer works:

![image](https://cloud.githubusercontent.com/assets/17754242/24384379/43e3b546-1318-11e7-96ca-cf4cecdc2970.png)

Previously this Statechart worked correctly, but now any references to a state in another region generate an error. This has broken numerous Statecharts. Is this is a bug, or did the syntax change?

**Comment by andreasmuelder** [comment]
@elgeekomm I think you missed the statechart prefix in the reference, this model is working (no errors, can be simulated and generated) with the latest release:

![isactive](https://cloud.githubusercontent.com/assets/6338708/24396704/65421b92-13a4-11e7-961b-8ecda28ea013.PNG)

However, the code completion is broken and the linking when the embedded editor is open seems to be broken. We will fix this ASAP and provide a bugfix release. Thanks for reporting.

**Comment by andreasmuelder** [comment]
fixed via PR #1295

**Comment by elgeekomm** [comment]
Thanks for the quick response Andreas. I'm afraid this has broken our build. A few questions that may help get us get back online:

1. In which version was the `active(state)` syntax changed? I may have missed this in a changelog or blog.
2. The current documentation on statecharts.org references the old syntax, 6.9.3 `active(state)`. Is this no longer the case?
3. Is the `active(StateIsActive.state)` backwards compatible with older versions of Yakindu?
4. We have a team of 25 developers who use our development environment with varying regularity. We have 18 statecharts in our code repository, each with dozens of states. This change breaks almost all of them. The only resolution that comes to mind is to update every broken statechart with the new syntax and then refactor into any feature branches, and simultaneously have every developer update their Yakindu version. Is there an easier migration path?

Thanks in advance for any advice / suggestions regarding this issue.

**Comment by andreasmuelder** [comment]
Too bad with your build, but I am afraid I didn't catch the problem yet.

We didn't change the 'active' syntax. It was always 
active(<statechartname>.<region>.<statename>)
(In my example above the name of the Statechart is 'StateIsActive')

I just checked this with a really old 2.4 release from 2014 and it did not work there, too.
![unbenannt](https://cloud.githubusercontent.com/assets/6338708/24421592/f4c0519c-13f6-11e7-8e51-d21f02d6a6fe.png)

What I have seen so far is that if you ignore this error message in the embedded editor and close it, the error marker gets away and you can generate code out of it. But this did only work due to a side effect and I doubt that this is the way all your statecharts are created??

So it would be helpful if you can send me a statechart and tell me the exact version you have been using by now.

**Comment by elgeekomm** [comment]
I think I understand the problem. It looks like we were taking advantage of namespace resolution, which has recently changed. Up to at least version 2.9.0 (and I think one or two releases after), the following works:

![image](https://cloud.githubusercontent.com/assets/17754242/24426088/421ccc22-13bb-11e7-899d-c0b6f04e766c.png)

This diagram generates successfully in 2.9.0 and no problems or errors are reported. On version 2.9.3, an error is shown, and code generation fails:

![image](https://cloud.githubusercontent.com/assets/17754242/24426204/b6f14adc-13bb-11e7-91f5-66d4c3b657d6.png)

> The referenced model(machine) contains errors and could not be generated:
> Couldn't resolve reference to State 'motor.running'.
> Couldn't resolve reference to State 'motor.stopped'.

The resolution is to add the complete scope:

![image](https://cloud.githubusercontent.com/assets/17754242/24426713/52ad8476-13bd-11e7-9884-68db0f976f77.png)

Model attached that works in 2.9.0 but is broken in 2.9.3.

The consequence is, for example, the guard `active(door.left_open)` becomes `active(machine.main_region.unlocked.unlocked.running.door.left_open)`. This affects dozens of transitions throughout our code.

[diagram.sct.txt](https://github.com/Yakindu/statecharts/files/877008/diagram.sct.txt)

**Comment by andreasmuelder** [comment]
We changed this with commit 12b0293ddd2fa677a976353fdb2c490a7994753d as a performance improvement for large models. 
We will restore the old behavior and will also ensure that no errors are reported in the embedded editors. 
I think we can provide a bug fix release until the end of this week. Is this ok for you?

**Comment by elgeekomm** [comment]
That will be amazing! Thanks for the quick response. We'll stay tuned to this issue.

**Comment by andreasmuelder** [comment]
@elgeekomm I just build an integration release for testing. It would be great if you could install it to see if everything is as you expect. Just download the latest SCT release, click help -> install new software and enter http://updates.yakindu.org/sct/integration as the work with URL.

**Comment by elgeekomm** [comment]
Beautiful. Installed the 2017-04-03 integration release and everything works great.

**Comment by andreasmuelder** [comment]
Unfortunately this commit did not pass our QA due to some performance drawbacks with large models.
I will release a bugfix release with the old behavior prior 2.9.0 today to ensure that your models are working and create a new fix for the error in the embedded editor for the upcoming release scheduled for 28th of April.

**Comment by elgeekomm** [comment]
Thanks Adreas, this will work for us. Are you pushing the bug fix to the main install path (i.e. just a standard Eclipse update)?

**Comment by andreasmuelder** [comment]
Yes it should now be available via eclipse update

**Comment by elgeekomm** [comment]
I installed the 2017-04-06 eclipse update and the build works, with one exception. I noticed with both the 2017-04-03 integration release, and with the 2017-04-06 release, the attached model is broken. It's derived from a model that worked in previous releases. I have to comment out a line for it to work now.

![image](https://cloud.githubusercontent.com/assets/17754242/24810797/76a54568-1b78-11e7-839c-4684b8339486.png)

[default.sct.txt](https://github.com/Yakindu/statecharts/files/906255/default.sct.txt)

**Comment by andreasmuelder** [comment]
@elgeekomm It would be great if you could create a new issue for that. We can fix this for the upcoming planned release in 4 weeks.

**Comment by elgeekomm** [comment]
@andreasmuelder done! https://github.com/Yakindu/statecharts/issues/1310

**Comment by BeckmaR** [comment]
@andreasmuelder, @elgeekomm - please clarify the current state of this issue. What needs to be done?

**Comment by elgeekomm** [comment]
I believe this issue has been resolved. The latest version of the tools is working well for us.

**Comment by andreasmuelder** [comment]
It is not completely fixed yet - it still shows an error in the embedded editor. But at least it is not a high priority issue anymore.

**Comment by andreasmuelder** [comment]
Latest version does support implicit imports for parent region names and navigation to referenced state with CTRL + Click
