### ISSUE TITLE
Python code generator doesn't support hyphens in folder names

### ISSUE THREAD

**Issue by bbpaulvanharen** [Yakindu/statecharts#3214]
The default .sgen file for c code generation uses a line 
`const FOLDER : string = "src-gen"`

The same line in the .sgen file for a python project reports an invalid name for the folder. Hence, the project won't compile

**Comment by tkutz** [comment]
This is already fixed in version 4.0.2.

**Comment by bbpaulvanharen** [comment]
I just upgraded to version 4.0.3 and the problem still persists. 
Noteworthy details: 
- version 4.0.3 is not mentioned in the release notes
- the pathname issue is not mentioned in the release notes

**Comment by tkutz** [comment]
4.0.3 is freshly released. Release notes will be updated asap.

The default sgen for the python generator should not contain a hyphen anymore. But hyphens are still not allowed, as they are not allowed for package names.

**Comment by bbpaulvanharen** [comment]
Thx
